### ISSUE TITLE
Background video playback is incorrectly paused

### ISSUE THREAD

**Issue by defagos** [SRGSSR/playsrg-apple#198] opened 2021-12-14 12:06 UTC
As of version 3.4.0 background video playback does not work correctly anymore. This is not related to the iOS version, as I first incorrectly assumed. This regression is likely connected to the fixes made for PiP in 3.4.0.

### Issue type

Incorrect behavior

### Environment information

* Application version: 3.4.0
* iOS version: Tested on 14.8.1, 15.1 and 15.2
* Device: Physical

### Reproducibility

Always reproducible

### Steps to reproduce

1. Enable background video playback.
1. Play some video and reduce it into the mini player. Playback continues in the background.
1. Lock the device. Playback is incorrectly paused.

Note that background playback continues when the device is locked while the video layer is visible.

**Comment by pyby** [comment] 2021-12-17 15:52
The most common cases are fixed with [SRGMediaPlayer 6.2.1 release](https://github.com/SRGSSR/srgmediaplayer-apple/releases/tag/6.2.1). 

AirPods issue still persist, but I think, not new #199.

**Closed by pyby** 2021-12-17 15:52 UTC
Labels: minor bug

**Comment by ganti** [comment] 2022-03-06 17:20
The issue is still occurs, especially with audio only streams. A restart of the device helped, but it is annoying since it happens multiple time a week.
I use V 3.5.0 (373)

**Comment by defagos** [comment] 2022-03-07 06:17
Thanks for the feedback and sorry this issue affects you.

Background video playback (which this issue is originally about) is a tricky thing, but background audio (which the issue you describe is about) is usually pretty straightforward to implement.

I suspect the problem is related to iOS itself since we saw this issue raising recently, even if we didn't change anything to support audio playback in background (it's basically setting a flag to enable it, unlike background video playback which requires a substantial amount of additional work).

The fact that a device restart, usually a [forced](https://support.apple.com/en-gb/guide/iphone/iph8903c3ee6/ios) one, fixes the issue, is probably a sign this is (sadly) not related to the app itself. I could never reproduce it myself (maybe there is a reliable way but I could never identify one) so I never got the chance to debug what is happening and to report this issue to Apple if I can confirm the problem is on iOS side.

Which iOS version and which kind of device are you using, BTW?

**Comment by defagos** [comment] 2022-03-30 17:18
@ganti Thanks for the update. We'll keep listening to what our users say (through our official support channels or in App Store reviews) to see if the problem becomes more widespread than expected.

Usually [forced restarts](https://support.apple.com/en-gb/guide/iphone/iph8903c3ee6/ios) have always been a great help, but until one of our devices is affected (so that we can debug the issue) I sadly have no clue how we could get to the bottom of the story.

I hope the situation will improve on your side with further iOS updates. If we happen to be able to debug the issue we'll keep you posted.
